[package]
name = "io"
version = "0.1.0"
authors = ["Oliver Schneider <git-spam-no-reply9815368754983@oli-obk.de>", "The Rust Project Developers"]

[dependencies]

[features]
default = []
no_std = []
unstable = []
